# Basket of Indices

For your interviews.

## Index Basket Formulas

Given:
- $U_i(t)$: Units of relevant Component $i$ at time $t$.
- $P_i^*(t)$: Price of relevant Component $i$ at time $t$ (or if not available, use the price of Component $i$ in respect of the immediately following day).
- $I_0$: Initial index level set to 1000.00.
- EquityNotionalAmount$_{\text{Initial}} = 7.3453215$.

### Basket Units Calculation
The units of the Basket at time $t$, denoted as $B(t)$, can be calculated as follows:
$$B(t) = \sum_{i} U_i(t) \cdot \text{Adjustment Factor}$$
Where the Adjustment Factor accounts for any specific weighting or scaling needed.

### Basket Price Calculation
The price of the Basket at time $t$, denoted as $P(t)$, is calculated as:
$$P(t) = \frac{\sum_{i} U_i(t) \cdot P_i^*(t)}{B(t)}$$
This represents a weighted average of component prices, adjusted by their units in the basket.

### Component Units per Basket Unit Calculation
The units of relevant Component $i$ at time $t$ per unit of Basket, denoted as $C_i(t)$, are calculated as:
$$C_i(t) = \frac{U_i(t)}{B(t)}$$
This indicates the proportion of each component's units relative to the total basket units at time $t$.

## Initialisation
Initial values are set for the index calculation:
- $I_0 = 1000.00$
- EquityNotionalAmount$_{\text{Initial}} = 7.3453215$

In [28]:
import pandas as pd


def load_csv(file_path):
    return pd.read_csv(file_path, index_col=0)


def calculate_basket_units(units_df, EquityNotionalAmount_Initial=7.3453215):
    """
    Calculate the units of the Basket at time t as a scalar value.
    Incorporate EquityNotionalAmount_Initial if needed.
    """
    basket_units = units_df.sum().sum() * EquityNotionalAmount_Initial
    return basket_units


def calculate_basket_price(units_df, prices_df, basket_units):
    """
    Calculate the price of the Basket at time t as a scalar value.
    """
    total_value = ((units_df.sum().sum()) * prices_df)
    basket_price = total_value / basket_units
    return basket_price

def calculate_component_units_per_basket(units_df, basket_units):
    """
    Calculate the units of relevant Component i at time t per unit of Basket.
    """
    components = units_df/basket_units

    return components


units_df = load_csv('./data/Units.csv')
prices_df = load_csv('./data/Prices.csv')
units_df

   02-Jan-19  13-Jun-19  18-Oct-19
A      33.56      76.52      48.96
B      66.47      74.40      63.52
C      64.11      55.78      21.50
D      55.58      43.79      59.63

In [30]:
units = calculate_basket_units(units_df)
price = calculate_basket_price(units_df, prices_df, units)
components = calculate_component_units_per_basket(units, price)
components.to_csv('./data/components.csv', index=False)

components

                    A           B           C           D
Date
02-Jan-19  226.795700  354.188854  807.384512  263.970939
03-Jan-19  251.885343  367.716396  825.433901  271.865621
04-Jan-19  241.572757  351.374247  790.630838  259.627234
07-Jan-19  242.111654  350.926680  784.912929  259.439167
08-Jan-19  237.582600  348.400554  793.433251  251.284480
...               ...         ...         ...         ...
21-Jan-20  113.136358  215.108570  643.991315  161.739419
22-Jan-20  112.733953  216.147115  644.049217  161.827114
23-Jan-20  112.193644  214.824718  647.308458  162.975869
24-Jan-20  112.517913  217.011494  658.859032  164.336868
27-Jan-20  115.926774  220.702348  676.915081  166.684865

[269 rows x 4 columns]

With love from Adam.

## Github

Article here is also available on [Github](https://github.com/adamd1985/quant_research)

## Media

All media used (in the form of code or images) are either solely owned by me, acquired through licensing, or part of the Public Domain and granted use through Creative Commons License.

## CC Licensing and Use

<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.